name=YummyDSP
version=1.0.0
author=audio-dsp
maintainer=audio-dsp
sentence=Yummy DSP library for ESP32-P4 Audio Mixer
paragraph=DSP utilities
category=Signal Input/Output
url=https://github.com/REITZG1/audio-dsp
architectures=esp32
includes=YummyDSP.h
